### ISSUE TITLE
Make css rensponsive

### ISSUE THREAD

**Issue by melenaos** [melenaos/jquery-punchcard#1]
The design is fixed but it would be nice if it was rensponsive

**Comment by galczo5** [comment]
Ok, how do you image it? Github's punch cards are not responsive.

**Comment by melenaos** [comment]
You can see a live example at: [punchcard example](https://melenaos.github.io/jquery-punchcard/#examples)

**Comment by galczo5** [comment]
I know, I'll try to be more specific. How do you image responsive version? What should change on window resize?

**Comment by melenaos** [comment]
The same way an image would be resized. The height to width ratio stays the same and everything srinks when the boundaries get smaller. The same way an `<img style='width:100%' />` would respond to his parent resize. I cannot think of another implementable way, do you have any other idea?

**Comment by galczo5** [comment]
Ok, it sounds like a plan. I'll try to do it at my free time. Thanks for explanation!

**Comment by galczo5** [comment]
Hi, https://github.com/melenaos/jquery-punchcard/pull/7
Should resolve problem. Now on resize punchcard should behave like img tag. I've updated example.html to, so you can test it without any problem.

**Comment by melenaos** [comment]
Its working but after going to 80% it becomes unreadable. Can you put a swi8tch if someone doesn't want this feature?

**Comment by galczo5** [comment]
Yes, no problem. Do you prefer on/off switch or min-width like switch? Maybe both?

**Comment by melenaos** [comment]
Both would be great!


Από: galczo5
Αποστολή: Κυριακή, 1 Οκτωβρίου 2017 1:15 μμ
Προς: melenaos/jquery-punchcard
Κοιν.: melenaos; Author
Θέμα: Re: [melenaos/jquery-punchcard] Make css rensponsive (#1)

Yes, no problem. Do you prefer on/off switch or min-width like switch? Maybe both?

**Comment by galczo5** [comment]
https://github.com/melenaos/jquery-punchcard/pull/8

Solution. Here https://gist.github.com/galczo5/9a2df391e625b08e1cfea0d1c5d5ad18 you can find example.html with tests. By default punchcard is not responsive. I can change it if you want.

**Comment by melenaos** [comment]
works perfect, thank you
