### ISSUE TITLE
Implement AJAX datasource

### ISSUE THREAD

**Issue by melenaos** [melenaos/jquery-punchcard#3]
There is an option at the initialization of the plugin 'ajax' that if set ti must retrieve the datasource from the server rather just use the data option provided.

When the function refresh is called then it must get again from the server the new data

**Comment by pisinr** [comment]
Instead of having a ajax option, I would rather make `data` key accept either a function or a promise.
A function would result in a function call and the result is used.
If result of the function, or the data itself, is promise then the promise result is used as the data.

What do you think?

**Comment by melenaos** [comment]
so it can be like 
`data:[[0,0],[9,0],..[]]`
or `data:function(){ $.get('\ajax');}`

it sound good. is it a common practice?

**Comment by pisinr** [comment]
It seem more extensible to me. Any one can then plugin their data source, AJAX or not.
I think it is common enough with many libraries optionally taking then-able object as data.

**Comment by melenaos** [comment]
Can you work on that? It would be perfect

**Comment by pisinr** [comment]
Will look into it.
