### ISSUE TITLE
Create a better logo for the project

### ISSUE THREAD

**Issue by melenaos** [melenaos/jquery-punchcard#5]
The current logo is designed by me but i don't really like it. Is there any actual designer to help me with this?

**Comment by isuruAb** [comment]
hello @melenaos  i would like to work on this

**Comment by melenaos** [comment]
Hi @isuruAb. It would be great if you want to work on this. Please let me know if you need any information that can help.

**Comment by mlavrent** [comment]
Hey, I was wondering if you liked the following:

![snip](https://user-images.githubusercontent.com/12854315/31024308-a2bedf06-a50c-11e7-9930-dd960e3ef389.PNG)

**Comment by melenaos** [comment]
Thank you @MLavrentyev but @isuruAb  is working on this issue.

**Comment by isuruAb** [comment]
@melenaos  please check this. ![index](https://user-images.githubusercontent.com/7692626/31082954-e2688ed8-a7ad-11e7-8b3c-474ea5f33352.png)

**Comment by melenaos** [comment]
@isuruAb This is great! I really like it and i would like to share with you that when i read it i stuck somewhere in the middle... somewhere at the ..nchc.. letters.
Can you put a color there or a shade of gray, or change the typewriting of card so it can be read with ease?

**Comment by isuruAb** [comment]
@melenaos please check these two
![index1](https://user-images.githubusercontent.com/7692626/31089265-152a832c-a7c1-11e7-97d4-b3d5748d2257.png)
![index2](https://user-images.githubusercontent.com/7692626/31089266-152c5382-a7c1-11e7-884d-3cb3c6a7ec4a.png)
![index3](https://user-images.githubusercontent.com/7692626/31089325-3ec20db8-a7c1-11e7-8d58-d8f004158ffe.png)
![index4](https://user-images.githubusercontent.com/7692626/31089735-cba62a10-a7c2-11e7-9fb7-735c193de788.png)
![index5](https://user-images.githubusercontent.com/7692626/31089810-0ce11c1a-a7c3-11e7-9985-851072459ce5.png)

**Comment by melenaos** [comment]
I like them both! I guess the gray is more serious. So I would choose the orange! 

Create a pull request with the new logo so it can count for hacktoberfest.
